### ISSUE TITLE
PWA Checklist: Icons for Polaris App

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris-2018#14]
## Requirement
favicon and icon is needed for the demo app. This is a subtask required to make the app PWA.

## Tasks
1. Create icons in client folder.
2. Icons should be clean and should not infringe on copyright. Even a clear 'P' with a background is enough for demo purposes.
3. in client folder, create a public/images folder and create icons of these sizes required for PWA.

- 48x48
- 72x72 
- 96x96 
- 128x128 
- 256x256

4. Create a 16x16 favicon.ico as well to be used as favicon.

## Please Note
This issue is being tagged as `hacktoberfest` and thus seeing a lot of traffic. If you're going to work on it and raise a PR, please comment. First preference to merge the project will be given to the first comment. However, the person has 24 hours of time to raise the PR. After that, the issue will be open for contribution again.

**Comment by digilou** [comment]
@tanaypratap I'd love to take this one, too. PWAs are something I've been practicing lately, and I love design work. I'll try to have a mock up at the end of the day.

**Comment by digilou** [comment]
@tanaypratap Does this meet your approval?
![asset 3 0 5x](https://user-images.githubusercontent.com/8865558/46565580-32b69200-c8bd-11e8-9ca2-9fad645fa537.png)

**Comment by digilou** [comment]
If you want 2018 in there somewhere, I can work that in, too.
