### ISSUE TITLE
Add support for React Router 4

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris-2018#4]
1. Add RR4 support.
2. Create two example React Components: Home and About (content can be taken from project readme)
3. Create Nav Bar on top and handle routing through React Router.
4. Add a how-to-add-routes.md doc for other people to use React Router.

Note: Use HTML5 routing, no hash required.

**Comment by lucchmielowski** [comment]
Hi ! Can I help on this issue ? :smiley:

**Comment by tanaypratap** [comment]
Yes. please go ahead. Do you need any help from my side on this one?

**Comment by tanaypratap** [comment]
@lucchmielowski update on this?
